name: run reminder
on: push

jobs:
  build:
    name: run script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.date.outputs.today }}
          body: |
            ## foo
