name: run reminder
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: run script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get today's date
        id: date
        run: |
          echo "::set-output name=today::$(date "+%Y/%m/%d")"

      - name: Run script
        id: script
        run: |
          chmod +x ./request_atcoder.sh 
          description=$(bash ./request_atcoder.sh)
          description="${description//'%'/'%25'}"
          description="${description//$'\n'/'%0A'}"
          description="${description//$'\r'/'%0D'}"
          echo $description
          echo "::set-output name=body::$description"

      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "Atcoder復習✍️ ${{ steps.date.outputs.today }}"
          body: |
            ${{ steps.script.outputs.body }}
