name: run reminder
on: push

jobs:
  build:
    name: run script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get today's date
        id: date
        run: |
          echo "::set-output name=today::$(date "+%Y/%m/%d")"

      - name: Run script
        id: script
        run: |
          chmod +x ./request_atcoder.sh 
          echo "::set-output name=body::$(bash ./request_atcoder.sh)"

      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "Atcoder復習✍️ ${{ steps.date.outputs.today }}"
          body: ${{ steps.script.outputs.body }}
